services:
  - type: web
    name: nomic-embed-service
    env: python
    plan: free # El plan gratuito puede ser lento, considera uno de pago si necesitas más rendimiento.
    buildCommanpip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: "3.10.13" # Asegura que Render use la versión correcta
