services:
  - type: web
    name: nomic-embed-service
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: NOMIC_API_KEY
        value: tu_clave_aqui
