name: Keep Nomic Alive

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  keepalive:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Nomic API (retry & longer timeout)
        run: curl -s --max-time 30 --retry 3 https://nomic-embed-api.onrender.com/embed

